version: '3'

services:
  db:
    build:
      context: ./docker/mysql
      args:
        mysql_version: ${MYSQL_VERSION}
    container_name: ${COMPOSE_PROJECT_NAME}-mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${MYSQL_PORT}:3306"
    restart: always
  app:
    build:
      context: ./docker/php
      args:
        php_version: ${PHP_VERSION}
    container_name: ${COMPOSE_PROJECT_NAME}-php
    ports:
      - "${PHP_PORT}:80"
    volumes:
      - ./${PHP_DIRECTORY}:/var/www/html
    links:
      - db
  phpmyadmin:
    image: 'phpmyadmin/phpmyadmin:latest'
    depends_on:
        - db
    ports:
        - "${PHPMYADMIN_PORT}:80"
    container_name: ${COMPOSE_PROJECT_NAME}-phpmyadmin
    environment:
        MYSQL_USERNAME: "${MYSQL_USER}"
        MYSQL_ROOT_PASSWORD: "${MYSQL_PASSWORD}"
        PMA_HOST: db

